#!/bin/sh
for f in $(git diff --name-only --cached); do
    if [[ $f == *.ipynb ]]; then
		has_content="$(cat $f | underscore select '.cells' | underscore flatten --shallow | underscore any 'value?.outputs?.length > 0')"
		if $has_content
		then
			echo -e 'Notebook ' $f ' \033[0;31moutput cells are not clean!\033[0m'
			git reset
			#echo 'Unstage ' $f ' file and clean its cell outputs'
			exit 1
		fi
    fi
done
